import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { ShoppingCart, Menu, X } from 'lucide-react';
import { useState } from 'react';
export function Header({ onCheckoutClick, onHomeClick, currentPage }) {
    const [mobileMenuOpen, setMobileMenuOpen] = useState(false);
    return (_jsx("header", { className: "bg-white border-b border-gray-200 sticky top-0 z-50 shadow-sm", children: _jsxs("div", { className: "max-w-7xl mx-auto px-4 md:px-6 py-4", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("button", { onClick: onHomeClick, className: "flex items-center gap-2 hover:opacity-80 transition", children: [_jsx("div", { className: "w-10 h-10 bg-[#FF7A59] rounded-lg flex items-center justify-center", children: _jsx("span", { className: "text-white font-bold text-xl", children: "\uD83D\uDC15" }) }), _jsxs("div", { className: "text-left", children: [_jsx("h1", { className: "text-xl font-bold text-gray-900", children: "Happy Dog Bites" }), _jsx("p", { className: "text-xs text-gray-500", children: "Premium Nutrition" })] })] }), _jsxs("nav", { className: "hidden md:flex items-center gap-8", children: [_jsx("button", { onClick: onCheckoutClick, className: "text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Shop" }), _jsx("a", { href: "#about", className: "text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "About" }), _jsx("a", { href: "#testimonials", className: "text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Reviews" }), _jsx("a", { href: "#faq", className: "text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "FAQ" }), _jsx("a", { href: "mailto:support@dogfood.com", className: "text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Contact" })] }), _jsxs("div", { className: "flex items-center gap-4", children: [currentPage !== 'checkout' && currentPage !== 'confirmation' && (_jsxs("button", { onClick: onCheckoutClick, className: "hidden sm:flex items-center gap-2 bg-[#FF7A59] hover:bg-[#ff6844] text-white px-4 py-2 rounded-lg transition font-semibold text-sm", children: [_jsx(ShoppingCart, { className: "w-4 h-4" }), _jsx("span", { children: "Shop Now" })] })), _jsx("button", { onClick: () => setMobileMenuOpen(!mobileMenuOpen), className: "md:hidden p-2 hover:bg-gray-100 rounded-lg transition", children: mobileMenuOpen ? (_jsx(X, { className: "w-6 h-6 text-gray-900" })) : (_jsx(Menu, { className: "w-6 h-6 text-gray-900" })) })] })] }), mobileMenuOpen && (_jsxs("nav", { className: "md:hidden mt-4 pb-4 space-y-3 border-t border-gray-200 pt-4", children: [_jsx("button", { onClick: () => {
                                onCheckoutClick?.();
                                setMobileMenuOpen(false);
                            }, className: "block w-full text-left text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Shop" }), _jsx("a", { href: "#about", onClick: () => setMobileMenuOpen(false), className: "block text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "About" }), _jsx("a", { href: "#testimonials", onClick: () => setMobileMenuOpen(false), className: "block text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Reviews" }), _jsx("a", { href: "#faq", onClick: () => setMobileMenuOpen(false), className: "block text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "FAQ" }), _jsx("a", { href: "mailto:support@dogfood.com", onClick: () => setMobileMenuOpen(false), className: "block text-sm font-medium text-gray-700 hover:text-[#FF7A59] transition", children: "Contact" }), currentPage !== 'checkout' && currentPage !== 'confirmation' && (_jsx("button", { onClick: () => {
                                onCheckoutClick?.();
                                setMobileMenuOpen(false);
                            }, className: "w-full bg-[#FF7A59] hover:bg-[#ff6844] text-white px-4 py-2 rounded-lg transition font-semibold text-sm", children: "Shop Now" }))] }))] }) }));
}
//# sourceMappingURL=Header.js.map